kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: ejb-txn-remote-call-client
  labels:
    app.kubernetes.io/name: ejb-txn-remote-call-client
    app.openshift.io/runtime: wildfly  
spec:
  replicas: 1
  serviceName: ejb-txn-remote-call-client-headless
  selector:
    matchLabels: 
      app.kubernetes.io/name: ejb-txn-remote-call-client 
  template:
    metadata: 
      labels: 
        app.kubernetes.io/name: ejb-txn-remote-call-client 
      annotations:
        wildfly.org/server-type: bootable-jar
    spec:
      volumes:
        - name: ejb-txn-remote-call-client-volume
          emptyDir: {}
      containers:
        - name: ejb-txn-remote-call-client
          image: ghcr.io/robert0714/ejb-txn-remote-call-client:latest
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: admin
              containerPort: 9990
              protocol: TCP
          env:
            - name: TZ
              value: Asia/Taipei
            - name: POSTGRESQL_SERVICE_HOST
              value: postgresql-database-service.database.svc.cluster.local
            - name: POSTGRESQL_SERVICE_PORT
              value: '5432'
            - name: POSTGRESQL_USER
              value: todos
            - name: POSTGRESQL_PASSWORD
              value: mysecretpassword
            - name: POSTGRESQL_DATASOURCE
              value: ejbJtaDs
            - name: POSTGRESQL_DATABASE
              value: todos
            - name: POSTGRESQL_URL
              value: >-
                jdbc:postgresql://${env.POSTGRESQL_SERVICE_HOST}:${env.POSTGRESQL_SERVICE_PORT}/${env.POSTGRESQL_DATABASE}
            - name: POSTGRESQL_ENABLED
              value: 'true'
            - name: POSTGRESQL_VALIDATE_ON_MATCH
              value: 'false'
            - name: POSTGRESQL_BACKGROUND_VALIDATION
              value: 'true'
            - name: POSTGRESQL_BACKGROUND_VALIDATION_MILLIS
              value: '60000'
            - name: POSTGRESQL_FLUSH_STRATEGY
              value: IdleConnections
            - name: WILDFLY_TRACING_ENABLED
              value: 'true'
            - name: JAVA_OPTS
              value: >-
                -javaagent:/deployments/elastic-apm-agent-1.38.0.jar 
                -Delastic.apm.server_urls=http://apm.apm.svc.cluster.local:8200
                -Delastic.apm.service_name=client
                -Delastic.apm.application_packages=org.jboss.as.quickstarts.ejb.*
                -Delastic.apm.trace_methods=org.jboss.as.quickstarts.ejb.*
                -Delastic.apm.trace_methods_duration_threshold=100ms
                -Delastic.apm.stack_trace_limit=80 -Djboss.bind.address=0.0.0.0 
                -Xms300m  -Xmx600m  -Dwildfly.statistics-enabled=true
                -Dremote.server.host=ejb-txn-remote-call-server-headless
                -Dremote.server.port=8080
                -Dremote.server.username=quickstartUser
                -Dremote.server.password=quickstartPwd1! 
                -Drmote.ejb.hostsAndPorts[0]=ejb-txn-remote-call-server-0.ejb-txn-remote-call-server-headless:8080
                -Drmote.ejb.hostsAndPorts[1]=ejb-txn-remote-call-server-1.ejb-txn-remote-call-server-headless:8080
                -Drmote.ejb.hostsAndPorts[2]=ejb-txn-remote-call-server-2.ejb-txn-remote-call-server-headless:8080
                -Drmote.ejb.hostsAndPorts[3]=ejb-txn-remote-call-server-3.ejb-txn-remote-call-server-headless:8080
                -Drmote.ejb.hostsAndPorts[4]=ejb-txn-remote-call-server-4.ejb-txn-remote-call-server-headless:8080
                -Drmote.ejb.hostsAndPorts[5]=ejb-txn-remote-call-server-5.ejb-txn-remote-call-server-headless:8080
                -Drmote.ejb.hostsAndPorts[6]=ejb-txn-remote-call-server-6.ejb-txn-remote-call-server-headless:8080
                -Drmote.ejb.hostsAndPorts[7]=ejb-txn-remote-call-server-7.ejb-txn-remote-call-server-headless:8080
                -Drmote.ejb.hostsAndPorts[8]=ejb-txn-remote-call-server-8.ejb-txn-remote-call-server-headless:8080
                -Drmote.ejb.hostsAndPorts[9]=ejb-txn-remote-call-server-9.ejb-txn-remote-call-server-headless:8080      
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace            
            - name: STATEFULSET_HEADLESS_SERVICE_NAME
              value: ejb-txn-remote-call-client-headless
            - name: JAVA_ARGS
              value: >-
                -Djboss.server.data.dir=/opt/jboss/container/wildfly-bootable-jar-data/standalone/data
                --install-dir=/opt/jboss/container/wildfly-bootable-jar-server
            - name: JBOSS_HOME
              value: /opt/jboss/container/wildfly-bootable-jar-server
          resources:
            limits:
              cpu: 800m
              memory: 700Mi
            requests:
              cpu: 400m
              memory: 300Mi
          volumeMounts:
            - name: ejb-txn-remote-call-client-volume
              mountPath: /opt/jboss/container/wildfly-bootable-jar-data/standalone/data
          livenessProbe:
            httpGet:
              path: /health/live
              port: admin
              scheme: HTTP
            initialDelaySeconds: 60
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health/ready
              port: admin
              scheme: HTTP
            initialDelaySeconds: 60
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      
---
kind: Service
apiVersion: v1
metadata:
  name: ejb-txn-remote-call-client-admin 
  labels: 
    app.kubernetes.io/name: ejb-txn-remote-call-client   
spec:
  ports:
    - name: admin
      protocol: TCP
      port: 9990
      targetPort: 9990
  selector: 
    app.kubernetes.io/name: ejb-txn-remote-call-client 
  clusterIP: None
  clusterIPs:
    - None
  type: ClusterIP
  sessionAffinity: None
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  internalTrafficPolicy: Cluster

---
kind: Service
apiVersion: v1
metadata:
  name: ejb-txn-remote-call-client-loadbalancer
  labels:
    app.kubernetes.io/managed-by: wildfly-operator
    app.kubernetes.io/name: ejb-txn-remote-call-client
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector: 
    app.kubernetes.io/name: ejb-txn-remote-call-client
  type: ClusterIP
  sessionAffinity: None
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  internalTrafficPolicy: Cluster 
---
kind: Service
apiVersion: v1
metadata:
  name: ejb-txn-remote-call-client-headless
  labels: 
    app.kubernetes.io/name: ejb-txn-remote-call-client 
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector: 
    app.kubernetes.io/name: ejb-txn-remote-call-client 
  clusterIP: None
  clusterIPs:
    - None
  type: ClusterIP
  sessionAffinity: None
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  internalTrafficPolicy: Cluster 