kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: ejb-txn-remote-call-server
  namespace: default
  uid: 5f29d3c5-c264-4cf3-a976-01ce796569b5
  resourceVersion: '1598'
  generation: 4
  creationTimestamp: '2023-06-12T05:16:37Z'
  labels:
    app.kubernetes.io/managed-by: wildfly-operator
    app.kubernetes.io/name: ejb-txn-remote-call-server
    app.openshift.io/runtime: wildfly
  annotations:
    image.openshift.io/triggers: >-
      [{ "from": { "kind":"ImageStreamTag",
      "name":"ghcr.io/robert0714/ejb-txn-remote-call-server:latest"},
      "fieldPath":
      "spec.template.spec.containers[?(@.name==\"ejb-txn-remote-call-server\")].image"}]
    wildfly.org/wildfly-server-generation: '2'
  ownerReferences:
    - apiVersion: wildfly.org/v1alpha1
      kind: WildFlyServer
      name: ejb-txn-remote-call-server
      uid: 5abc9e51-15b1-4dae-8ccf-51a1fb70bd25
      controller: true
      blockOwnerDeletion: true
  managedFields:
    - manager: wildfly-operator
      operation: Update
      apiVersion: apps/v1
      time: '2023-06-12T05:31:01Z'
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:image.openshift.io/triggers: {}
            f:wildfly.org/wildfly-server-generation: {}
          f:labels:
            .: {}
            f:app.kubernetes.io/managed-by: {}
            f:app.kubernetes.io/name: {}
            f:app.openshift.io/runtime: {}
          f:ownerReferences:
            .: {}
            k:{"uid":"5abc9e51-15b1-4dae-8ccf-51a1fb70bd25"}: {}
        f:spec:
          f:podManagementPolicy: {}
          f:replicas: {}
          f:revisionHistoryLimit: {}
          f:selector: {}
          f:serviceName: {}
          f:template:
            f:metadata:
              f:annotations:
                .: {}
                f:wildfly.org/server-type: {}
              f:labels:
                .: {}
                f:app.kubernetes.io/managed-by: {}
                f:app.kubernetes.io/name: {}
                f:app.openshift.io/runtime: {}
                f:wildfly.org/operated-by-headless: {}
                f:wildfly.org/operated-by-loadbalancer: {}
            f:spec:
              f:containers:
                k:{"name":"ejb-txn-remote-call-server"}:
                  .: {}
                  f:env:
                    .: {}
                    k:{"name":"JAVA_ARGS"}:
                      .: {}
                      f:name: {}
                      f:value: {}
                    k:{"name":"JAVA_OPTS"}:
                      .: {}
                      f:name: {}
                      f:value: {}
                    k:{"name":"JBOSS_HOME"}:
                      .: {}
                      f:name: {}
                      f:value: {}
                    k:{"name":"KUBERNETES_LABELS"}:
                      .: {}
                      f:name: {}
                      f:value: {}
                    k:{"name":"KUBERNETES_NAMESPACE"}:
                      .: {}
                      f:name: {}
                      f:valueFrom:
                        .: {}
                        f:fieldRef: {}
                    k:{"name":"POSTGRESQL_BACKGROUND_VALIDATION"}:
                      .: {}
                      f:name: {}
                      f:value: {}
                    k:{"name":"POSTGRESQL_BACKGROUND_VALIDATION_MILLIS"}:
                      .: {}
                      f:name: {}
                      f:value: {}
                    k:{"name":"POSTGRESQL_DATABASE"}:
                      .: {}
                      f:name: {}
                      f:value: {}
                    k:{"name":"POSTGRESQL_DATASOURCE"}:
                      .: {}
                      f:name: {}
                      f:value: {}
                    k:{"name":"POSTGRESQL_ENABLED"}:
                      .: {}
                      f:name: {}
                      f:value: {}
                    k:{"name":"POSTGRESQL_FLUSH_STRATEGY"}:
                      .: {}
                      f:name: {}
                      f:value: {}
                    k:{"name":"POSTGRESQL_PASSWORD"}:
                      .: {}
                      f:name: {}
                      f:value: {}
                    k:{"name":"POSTGRESQL_SERVICE_HOST"}:
                      .: {}
                      f:name: {}
                      f:value: {}
                    k:{"name":"POSTGRESQL_SERVICE_PORT"}:
                      .: {}
                      f:name: {}
                      f:value: {}
                    k:{"name":"POSTGRESQL_URL"}:
                      .: {}
                      f:name: {}
                      f:value: {}
                    k:{"name":"POSTGRESQL_USER"}:
                      .: {}
                      f:name: {}
                      f:value: {}
                    k:{"name":"POSTGRESQL_VALIDATE_ON_MATCH"}:
                      .: {}
                      f:name: {}
                      f:value: {}
                    k:{"name":"STATEFULSET_HEADLESS_SERVICE_NAME"}:
                      .: {}
                      f:name: {}
                      f:value: {}
                    k:{"name":"TZ"}:
                      .: {}
                      f:name: {}
                      f:value: {}
                    k:{"name":"WILDFLY_TRACING_ENABLED"}:
                      .: {}
                      f:name: {}
                      f:value: {}
                  f:image: {}
                  f:imagePullPolicy: {}
                  f:livenessProbe:
                    .: {}
                    f:failureThreshold: {}
                    f:httpGet:
                      .: {}
                      f:path: {}
                      f:port: {}
                      f:scheme: {}
                    f:initialDelaySeconds: {}
                    f:periodSeconds: {}
                    f:successThreshold: {}
                    f:timeoutSeconds: {}
                  f:name: {}
                  f:ports:
                    .: {}
                    k:{"containerPort":8080,"protocol":"TCP"}:
                      .: {}
                      f:containerPort: {}
                      f:name: {}
                      f:protocol: {}
                    k:{"containerPort":9990,"protocol":"TCP"}:
                      .: {}
                      f:containerPort: {}
                      f:name: {}
                      f:protocol: {}
                  f:readinessProbe:
                    .: {}
                    f:failureThreshold: {}
                    f:httpGet:
                      .: {}
                      f:path: {}
                      f:port: {}
                      f:scheme: {}
                    f:initialDelaySeconds: {}
                    f:periodSeconds: {}
                    f:successThreshold: {}
                    f:timeoutSeconds: {}
                  f:resources:
                    .: {}
                    f:limits:
                      .: {}
                      f:cpu: {}
                      f:memory: {}
                    f:requests:
                      .: {}
                      f:cpu: {}
                      f:memory: {}
                  f:terminationMessagePath: {}
                  f:terminationMessagePolicy: {}
                  f:volumeMounts:
                    .: {}
                    k:{"mountPath":"/opt/jboss/container/wildfly-bootable-jar-data/standalone/data"}:
                      .: {}
                      f:mountPath: {}
                      f:name: {}
              f:dnsPolicy: {}
              f:restartPolicy: {}
              f:schedulerName: {}
              f:securityContext: {}
              f:terminationGracePeriodSeconds: {}
              f:volumes:
                .: {}
                k:{"name":"ejb-txn-remote-call-server-volume"}:
                  .: {}
                  f:emptyDir: {}
                  f:name: {}
          f:updateStrategy:
            f:rollingUpdate:
              .: {}
              f:partition: {}
            f:type: {}
    - manager: kube-controller-manager
      operation: Update
      apiVersion: apps/v1
      time: '2023-06-12T05:33:28Z'
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          f:availableReplicas: {}
          f:currentReplicas: {}
          f:observedGeneration: {}
          f:readyReplicas: {}
          f:replicas: {}
          f:updatedReplicas: {}
      subresource: status
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/managed-by: wildfly-operator
      app.kubernetes.io/name: ejb-txn-remote-call-server
      app.openshift.io/runtime: wildfly
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/managed-by: wildfly-operator
        app.kubernetes.io/name: ejb-txn-remote-call-server
        app.openshift.io/runtime: wildfly
        wildfly.org/operated-by-headless: active
        wildfly.org/operated-by-loadbalancer: active
      annotations:
        wildfly.org/server-type: bootable-jar
    spec:
      volumes:
        - name: ejb-txn-remote-call-server-volume
          emptyDir: {}
      containers:
        - name: ejb-txn-remote-call-server
          image: ghcr.io/robert0714/ejb-txn-remote-call-server:latest
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: admin
              containerPort: 9990
              protocol: TCP
          env:
            - name: TZ
              value: Asia/Taipei
            - name: POSTGRESQL_SERVICE_HOST
              value: postgresql-database-service.database.svc.cluster.local
            - name: POSTGRESQL_SERVICE_PORT
              value: '5432'
            - name: POSTGRESQL_USER
              value: todos
            - name: POSTGRESQL_PASSWORD
              value: mysecretpassword
            - name: POSTGRESQL_DATASOURCE
              value: ejbJtaDs
            - name: POSTGRESQL_DATABASE
              value: todos
            - name: POSTGRESQL_URL
              value: >-
                jdbc:postgresql://${env.POSTGRESQL_SERVICE_HOST}:${env.POSTGRESQL_SERVICE_PORT}/${env.POSTGRESQL_DATABASE}
            - name: POSTGRESQL_ENABLED
              value: 'true'
            - name: POSTGRESQL_VALIDATE_ON_MATCH
              value: 'false'
            - name: POSTGRESQL_BACKGROUND_VALIDATION
              value: 'true'
            - name: POSTGRESQL_BACKGROUND_VALIDATION_MILLIS
              value: '60000'
            - name: POSTGRESQL_FLUSH_STRATEGY
              value: IdleConnections
            - name: WILDFLY_TRACING_ENABLED
              value: 'true'
            - name: JAVA_OPTS
              value: >-
                -javaagent:/app/elastic-apm-agent-1.33.0.jar 
                -Delastic.apm.server_urls=http://apm.apm.svc.cluster.local:8200
                -Delastic.apm.service_name=server
                -Delastic.apm.application_packages=org.jboss.as.quickstarts.ejb.*
                -Delastic.apm.trace_methods=org.jboss.as.quickstarts.ejb.*
                -Delastic.apm.trace_methods_duration_threshold=100ms
                -Delastic.apm.stack_trace_limit=80 -Djboss.bind.address=0.0.0.0 
                -Xms300m  -Xmx600m  -Dwildfly.statistics-enabled=true       
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: KUBERNETES_LABELS
              value: >-
                app.kubernetes.io/managed-by=wildfly-operator,app.kubernetes.io/name=ejb-txn-remote-call-server,app.openshift.io/runtime=wildfly
            - name: STATEFULSET_HEADLESS_SERVICE_NAME
              value: ejb-txn-remote-call-server-headless
            - name: JAVA_ARGS
              value: >-
                -Djboss.server.data.dir=/opt/jboss/container/wildfly-bootable-jar-data/standalone/data
                --install-dir=/opt/jboss/container/wildfly-bootable-jar-server
            - name: JBOSS_HOME
              value: /opt/jboss/container/wildfly-bootable-jar-server
          resources:
            limits:
              cpu: 800m
              memory: 700Mi
            requests:
              cpu: 400m
              memory: 300Mi
          volumeMounts:
            - name: ejb-txn-remote-call-server-volume
              mountPath: /opt/jboss/container/wildfly-bootable-jar-data/standalone/data
          livenessProbe:
            httpGet:
              path: /health/live
              port: admin
              scheme: HTTP
            initialDelaySeconds: 60
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health/ready
              port: admin
              scheme: HTTP
            initialDelaySeconds: 60
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  serviceName: ejb-txn-remote-call-server-headless
  podManagementPolicy: Parallel
  updateStrategy:
    type: RollingUpdate 

---
kind: Service
apiVersion: v1
metadata:
  name: ejb-txn-remote-call-server-admin
  labels:
    app.kubernetes.io/name: ejb-txn-remote-call-server'
spec:
  ports:
    - name: admin
      protocol: TCP
      port: 9990
      targetPort: 9990
  selector: 
    app.kubernetes.io/name: ejb-txn-remote-call-server 
  clusterIP: None
  clusterIPs:
    - None
  type: ClusterIP
  sessionAffinity: None
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  internalTrafficPolicy: Cluster 

---
kind: Service
apiVersion: v1
metadata:
  name: ejb-txn-remote-call-server-loadbalancer
  labels:
    app.kubernetes.io/managed-by: wildfly-operator
    app.kubernetes.io/name: ejb-txn-remote-call-server
    app.openshift.io/runtime: wildfly
    wildfly.org/operated-by-headless: active
    wildfly.org/operated-by-loadbalancer: active
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector: 
    app.kubernetes.io/name: ejb-txn-remote-call-server  
  type: ClusterIP
  sessionAffinity: None
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  internalTrafficPolicy: Cluster 

--- 
kind: Service
apiVersion: v1
metadata:
  name: ejb-txn-remote-call-server-headless
  labels:
    app.kubernetes.io/name: ejb-txn-remote-call-server
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector: 
    app.kubernetes.io/name: ejb-txn-remote-call-server
  clusterIP: None
  clusterIPs:
    - None
  type: ClusterIP
  sessionAffinity: None
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  internalTrafficPolicy: Cluster 