apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch
spec:
  selector:
    matchLabels:
      component: elasticsearch
  template:
    metadata:
      labels:
        component: elasticsearch
    spec:
      containers:
      - name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:7.17.10
        env:
        - name: discovery.type
          value: single-node
        - name: TZ
          value: 'Asia/Taipei'
        - name: INSTANCE_RAM
          value: 8Gi          
        - name: ES_JAVA_OPTS
          value: '-Xms2g -Xmx8g'
        - name: bootstrap.memory_lock
          value: 'true'
        - name: discovery.type
          value: 'single-node'
        - name: http.host
          value: '0.0.0.0'
        ports:
        - containerPort: 9200
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 4Gi
          requests:
            cpu: 500m
            memory: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  labels:
    service: elasticsearch
spec:
  type: NodePort
  selector:
    component: elasticsearch
  ports:
  - port: 9200
    targetPort: 9200
 