apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  labels:
    app: kibana 
spec:
  selector:
    matchLabels:
      run: kibana
  template:
    metadata:
      labels:
        run: kibana
    spec:
      containers:
        - name: kibana
          image: docker.elastic.co/kibana/kibana:7.17.10
          env:
           - name: ELASTICSEARCH_URL
             value: http://elasticsearch.default.svc.cluster.local:9200
           - name: TZ
             value: Asia/Taipei
          ports:
           - containerPort: 5601
             name: http
             protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: kibana
  labels:
    service: kibana
spec:
  type: NodePort
  selector:
    run: kibana
  ports:
  - port: 5601
    targetPort: 5601