name: ejb-txn-remote-call-client images ci

on:
  push:
    paths:
      - 'client/**'  
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8  
      - name: Compilling 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        working-directory: ./
        run:  | 
            echo $GITHUB_TOKEN | docker login ghcr.io -u USERNAME --password-stdin
            mvn install -Pbootable
            
      - name: Deploy Client App to Github Container Image Registry
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        working-directory: ./client/
        run:  |
            echo $GITHUB_TOKEN | docker login ghcr.io -u USERNAME --password-stdin
            
            docker build --build-arg GITHUB_TOKEN=$GITHUB_TOKEN -t ghcr.io/robert0714/ejb-txn-remote-call-client:latest .
            docker build --build-arg GITHUB_TOKEN=$GITHUB_TOKEN -t ghcr.io/robert0714/ejb-txn-remote-call-client:${{ steps.date.outputs.date }} .
            docker push ghcr.io/robert0714/ejb-txn-remote-call-client:latest
            docker push ghcr.io/robert0714/ejb-txn-remote-call-client:${{ steps.date.outputs.date }}
   